# Welcome to Jekyll!
#

# Site settings
title: Sagar Gantyala
description: Pursuing Msc in information systems management at NUIG, <br> travelling and learning new experiences
owner: Sagar Gantyala # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: s.gantyala1@nuigalway.ie
baseurl: "/SagarGantyala" # the subpath of your site, e.g. /blog
url: "https://sagarg007.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/sagarstf
  #github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/sagar-gantyala-baa819b7
  #facebook-official: https://facebook.com/sagargantyala
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/sagarstf
  youtube-square: https://www.youtube.com/channel/UC_kHSOoOcd3UVhePPmqBJag
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
